{{- if .Values.env.gcpEnabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.backendConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 60
{{- end }}